---
application:
  name: "soundbounce-v2"
  project: "private-soundbounce"
  organization: "CJP"
databases:
- type: "POSTGRESQL"
  name: "soundbounce"
  version: "11"
routers:
- name: "main-soundbounce-v2"
  routes:
  - application_name: "soundbounce-v2"
    paths:
    - "/*"
